"""Tests for the L2 bootstrap module (parse_processed_history + bootstrap_from_downloads + bootstrap_from_tree)."""

from pathlib import Path

import pytest
from pypdf import PdfWriter

from ocr_router.feedback import FeedbackLog
from ocr_router.feedback.bootstrap import (
    bootstrap_from_downloads,
    bootstrap_from_tree,
    index_history,
    infer_label_from_path,
    parse_processed_history,
    parse_processed_history_paths,
)


HISTORY_SAMPLE = """\
# Processed PDFs

Auto-generated by ocr-router — one section per day, one run per sub-heading.


---

## 2026-04-15

### 09:12 — 3 file(s) moved

| # | Original File | Category | Issuer | New Name | Amount | Destination |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | chase_apr.pdf | Bank Account & Statements | Chase Checking | 2026.04 - Chase Checking Statement.pdf | $1,200.00 | Bank Account & Statements\\Chase Checking\\2026\\2026.04 - Chase Checking Statement.pdf |
| 2 | fpl_bill.pdf | Bills | FPL | 2026.04 - FPL Monthly - $182.40.pdf | $182.40 | Bills\\FPL\\2026\\2026.04 - FPL Monthly - $182.40.pdf |
| 3 | tricky\\|name.pdf | Receipts | — | 2026.04.15 - Receipt.pdf | — | Receipts\\2026\\2026.04.15 - Receipt.pdf |


---

## 2026-05-01

### 14:00 — 1 file(s) renamed in place

| # | Original File | Category | Issuer | New Name | Amount | Final Path |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | amex_stmt.pdf | Credit Card Statements | AMEX | 2026.04 - AMEX Statement - $987.65.pdf | $987.65 | C:\\Users\\<user>\\downloads\\2026.04 - AMEX Statement - $987.65.pdf |
"""


def _make_blank_pdf(path: Path) -> Path:
    pdf = PdfWriter()
    pdf.add_blank_page(width=200, height=200)
    with open(path, "wb") as f:
        pdf.write(f)
    return path


# ---------------------------------------------------------------------------
# History parsing
# ---------------------------------------------------------------------------

def test_parse_history_returns_empty_on_missing_file(temp_dir):
    assert parse_processed_history(temp_dir / "nope.md") == []


def test_parse_history_extracts_all_rows(temp_dir):
    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE, encoding="utf-8")

    entries = parse_processed_history(hist)

    assert len(entries) == 4
    names = [e.original_filename for e in entries]
    assert "chase_apr.pdf" in names
    assert "fpl_bill.pdf" in names
    # The escaped pipe gets restored
    assert any("tricky|name.pdf" == e.original_filename for e in entries)
    assert "amex_stmt.pdf" in names


def test_parse_history_assigns_day_and_action_mode(temp_dir):
    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE, encoding="utf-8")
    entries = parse_processed_history(hist)

    chase = next(e for e in entries if e.original_filename == "chase_apr.pdf")
    assert chase.day == "2026-04-15"
    assert chase.action_mode == "move"
    assert chase.category == "Bank Account & Statements"
    assert chase.issuer == "Chase Checking"
    assert "Chase Checking" in chase.destination

    amex = next(e for e in entries if e.original_filename == "amex_stmt.pdf")
    assert amex.day == "2026-05-01"
    assert amex.action_mode == "rename"
    assert amex.issuer == "AMEX"


def test_parse_history_treats_dash_as_none(temp_dir):
    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE, encoding="utf-8")
    entries = parse_processed_history(hist)
    receipt = next(e for e in entries if e.original_filename == "tricky|name.pdf")
    assert receipt.issuer is None
    assert receipt.amount is None


def test_index_history_keeps_latest_day(temp_dir):
    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE + """
---

## 2026-05-15

### 10:00 — 1 file(s) moved

| # | Original File | Category | Issuer | New Name | Amount | Destination |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | chase_apr.pdf | Bank Account & Statements | Chase Savings | 2026.04 - Chase Savings Statement.pdf | $2,200.00 | Bank Account & Statements\\Chase Savings\\2026\\2026.04 - Chase Savings Statement.pdf |
""", encoding="utf-8")

    entries = parse_processed_history(hist)
    idx = index_history(entries)
    # The later 2026-05-15 entry must win
    assert idx["chase_apr.pdf"].issuer == "Chase Savings"
    assert idx["chase_apr.pdf"].day == "2026-05-15"


# ---------------------------------------------------------------------------
# bootstrap_from_downloads
# ---------------------------------------------------------------------------

def test_bootstrap_matches_files_and_appends_records(temp_dir):
    # arrange
    source = temp_dir / "downloads"
    source.mkdir()
    _make_blank_pdf(source / "chase_apr.pdf")
    _make_blank_pdf(source / "fpl_bill.pdf")
    _make_blank_pdf(source / "not_in_history.pdf")

    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE, encoding="utf-8")

    log = FeedbackLog(temp_dir / "_feedback" / "corrections.jsonl")

    # act — skip OCR so the test doesn't need Tesseract; blank PDFs have no text
    stats = bootstrap_from_downloads(
        source_dir=source,
        history_path=hist,
        feedback_log=log,
        ocr_engine=None,
        skip_ocr=True,
    )

    # assert
    assert stats.scanned == 3
    assert stats.matched == 2
    assert stats.appended == 2
    assert stats.no_history_match == 1

    records = list(log.iter_records())
    assert len(records) == 2
    cats = {r["final_category"] for r in records}
    assert cats == {"Bank Account & Statements", "Bills"}
    backends = {r["backend"] for r in records}
    assert backends == {"bootstrap"}
    events = {r["event"] for r in records}
    assert events == {"confirmed"}


def test_bootstrap_is_idempotent(temp_dir):
    source = temp_dir / "downloads"
    source.mkdir()
    _make_blank_pdf(source / "chase_apr.pdf")

    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE, encoding="utf-8")

    log = FeedbackLog(temp_dir / "log.jsonl")

    stats1 = bootstrap_from_downloads(source, hist, log, ocr_engine=None, skip_ocr=True)
    assert stats1.appended == 1

    stats2 = bootstrap_from_downloads(source, hist, log, ocr_engine=None, skip_ocr=True)
    assert stats2.appended == 0
    assert stats2.already_logged == 1
    assert len(list(log.iter_records())) == 1


def test_bootstrap_force_reimports(temp_dir):
    source = temp_dir / "downloads"
    source.mkdir()
    _make_blank_pdf(source / "chase_apr.pdf")

    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE, encoding="utf-8")

    log = FeedbackLog(temp_dir / "log.jsonl")
    bootstrap_from_downloads(source, hist, log, ocr_engine=None, skip_ocr=True)
    stats = bootstrap_from_downloads(source, hist, log, ocr_engine=None, skip_ocr=True, force=True)
    assert stats.appended == 1
    assert len(list(log.iter_records())) == 2  # one from first run + one from force


def test_bootstrap_include_unprocessed_emits_pending(temp_dir):
    source = temp_dir / "downloads"
    source.mkdir()
    _make_blank_pdf(source / "mystery.pdf")

    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE, encoding="utf-8")

    log = FeedbackLog(temp_dir / "log.jsonl")
    stats = bootstrap_from_downloads(
        source, hist, log, ocr_engine=None, skip_ocr=True, include_unprocessed=True,
    )
    assert stats.scanned == 1
    assert stats.matched == 0
    assert stats.appended == 1
    rec = list(log.iter_records())[0]
    assert rec["event"] == "pending"
    assert rec["original_filename"] == "mystery.pdf"


def test_bootstrap_handles_empty_source(temp_dir):
    source = temp_dir / "downloads"
    source.mkdir()
    hist = temp_dir / "PROCESSED_PDFS.md"
    hist.write_text(HISTORY_SAMPLE, encoding="utf-8")
    log = FeedbackLog(temp_dir / "log.jsonl")

    stats = bootstrap_from_downloads(source, hist, log, ocr_engine=None, skip_ocr=True)
    assert stats.scanned == 0
    assert stats.appended == 0


# ---------------------------------------------------------------------------
# Relaxed history parser (real-world format)
# ---------------------------------------------------------------------------

REAL_WORLD_SAMPLE = """\
# 2026.05 — Processed Downloads

## 2026-05-15 — 25 files processed

**Notes:** stuff happened.

| # | Original File | Category | Issuer | New Name | Amount | Destination |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | 911 Carrera T.pdf | — | — | 2025.12.29 - 911 Carrera T.pdf | — | __downloads__ (renamed in place) |
| 2 | canon receipt.pdf | Receipts | B&H Photo | 2025.11.18 - B&H Photo Receipt - $549.99.pdf | $549.99 | Receipts, Payment, Warranty |
| 3 | canon support page.pdf | — | — | — | — | DELETED |
| 4 | ContratoTarjetaCredito-BIP-4221.pdf | Credit Card Statements | AMEX Gold | 2024.08.10 - AMEX Gold Contract.pdf | — | Credit Card Statements\\AMEX Gold |

---

## 2026-05-25 (session 1) — 16 files processed

| #  | Original File | Category | Issuer | New Name | Amount | Destination |
| -- | ------------- | -------- | ------ | -------- | ------ | ----------- |
| 1  | 2026-04-27.pdf | Credit Card Statements | Fidelity Visa Signature | 2026.04 - Fidelity Visa (Last 9710) - $2,279.64.pdf | $2,279.64 | Credit Card Statements\\Fidelity Visa Signature\\2026 |
| 2  | 20260120-statements-5255-.pdf | Bank Account & Statements | Chase Checking | 2026.01 - Chase Checking.pdf | — | Bank Account & Statements\\Chase Checking\\2026 |

---

## Session 3 — 2026-05-25

### Duplicates deleted (16)

| File | Reason |
|---|---|
| `2026-01-27.pdf` | Already filed |

### Renamed in destination

| Location | Old Name | New Name |
|---|---|---|
| `foo` | bar | baz |

### Moved (34 files)

| # | Source | New Name | Destination |
|---|---|---|---|
| 1 | `c6f5bd7a-...pdf` | `2026.02 - Pennymac (8193759048).pdf` | `Mortgage\\PennyMac\\2026` |
"""


def test_parse_relaxed_skips_deletions(temp_dir):
    hist = temp_dir / "real.md"
    hist.write_text(REAL_WORLD_SAMPLE, encoding="utf-8")
    entries = parse_processed_history(hist)
    # 911 Carrera (no category), canon receipt, ContratoTarjetaCredito-BIP-4221,
    # 2026-04-27, 20260120-statements — 5 valid rows; DELETED row excluded,
    # Session 3 Moved table (only 4 cols) is excluded too.
    names = [e.original_filename for e in entries]
    assert "canon receipt.pdf" in names
    assert "ContratoTarjetaCredito-BIP-4221.pdf" in names
    assert "2026-04-27.pdf" in names
    assert "20260120-statements-5255-.pdf" in names
    # DELETED rows must not appear
    assert "canon support page.pdf" not in names
    # 4-col "Moved (34 files)" rows are not parseable as 7-col
    assert "c6f5bd7a-...pdf" not in names


def test_parse_relaxed_accepts_day_with_trailing_text(temp_dir):
    hist = temp_dir / "real.md"
    hist.write_text(REAL_WORLD_SAMPLE, encoding="utf-8")
    entries = parse_processed_history(hist)
    chase = next(e for e in entries if e.original_filename == "20260120-statements-5255-.pdf")
    assert chase.day == "2026-05-25"   # picks up the closest preceding day
    assert chase.category == "Bank Account & Statements"
    assert chase.issuer == "Chase Checking"


def test_parse_relaxed_session_n_day(temp_dir):
    # ``## Session 3 — 2026-05-25`` is a valid day heading via second pattern.
    hist = temp_dir / "real.md"
    hist.write_text(REAL_WORLD_SAMPLE, encoding="utf-8")
    entries = parse_processed_history(hist)
    # Session 3 is the LAST day section but contains no parseable 7-col rows,
    # so the parser falls through; no entry should claim that day.
    days = {e.day for e in entries}
    # only the two real day sections should appear
    assert days == {"2026-05-15", "2026-05-25"}


def test_parse_relaxed_strips_ocr_annotation(temp_dir):
    extra = REAL_WORLD_SAMPLE + """

## 2026-06-01 — sample

| # | Original File | Category | Issuer | New Name | Amount | Destination |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | Report_001035.pdf (OCR) | Health | Florida ENT | 2026.05.14 - Florida ENT EOB.pdf | — | Health\\2026 |
"""
    hist = temp_dir / "real.md"
    hist.write_text(extra, encoding="utf-8")
    entries = parse_processed_history(hist)
    rec = next(e for e in entries if "Report_001035" in e.original_filename)
    # The " (OCR)" suffix is stripped so it matches the real on-disk filename
    assert rec.original_filename == "Report_001035.pdf"


def test_parse_history_paths_accepts_directory(temp_dir):
    f1 = temp_dir / "2026.04 - PROCESSED_PDFS.md"
    f2 = temp_dir / "2026.05 - PROCESSED_PDFS.md"
    f1.write_text(HISTORY_SAMPLE, encoding="utf-8")
    f2.write_text(REAL_WORLD_SAMPLE, encoding="utf-8")

    entries = parse_processed_history_paths(temp_dir)
    # Multiple files merged
    names = {e.original_filename for e in entries}
    assert "chase_apr.pdf" in names           # from HISTORY_SAMPLE
    assert "canon receipt.pdf" in names       # from REAL_WORLD_SAMPLE


# ---------------------------------------------------------------------------
# Tree-based bootstrap
# ---------------------------------------------------------------------------

def test_infer_label_bills_issuer_year(temp_dir):
    root = temp_dir
    pdf = root / "Bills" / "FPL" / "2026" / "2026.04 - FPL.pdf"
    label = infer_label_from_path(pdf, root)
    assert label.category == "Bills"
    assert label.issuer == "FPL"
    assert label.year == "2026"
    assert label.final_filename == "2026.04 - FPL.pdf"


def test_infer_label_paystubs_year_only(temp_dir):
    root = temp_dir
    pdf = root / "Paystubs" / "2026" / "2026.05.01 - Paycheck.pdf"
    label = infer_label_from_path(pdf, root)
    assert label.category == "Paystubs"
    assert label.issuer is None
    assert label.year == "2026"


def test_infer_label_closed_accounts_skipped(temp_dir):
    root = temp_dir
    pdf = root / "Bank Account & Statements" / "_ Closed Accounts _" / "Old Bank" / "2018" / "x.pdf"
    label = infer_label_from_path(pdf, root)
    assert label.category == "Bank Account & Statements"
    assert label.issuer == "Old Bank"
    assert label.year == "2018"


def test_infer_label_file_directly_under_category(temp_dir):
    root = temp_dir
    pdf = root / "Personal" / "doc.pdf"
    label = infer_label_from_path(pdf, root)
    assert label.category == "Personal"
    assert label.issuer is None
    assert label.year is None


def test_bootstrap_from_tree_skips_excluded_dirs(temp_dir):
    root = temp_dir
    # Inside an excluded dir
    (root / "__downloads__").mkdir()
    _make_blank_pdf(root / "__downloads__" / "skipme.pdf")
    # Inside a real category
    (root / "Bills" / "FPL" / "2026").mkdir(parents=True)
    _make_blank_pdf(root / "Bills" / "FPL" / "2026" / "2026.04 - FPL.pdf")

    log = FeedbackLog(temp_dir / "log.jsonl")
    stats = bootstrap_from_tree(root, log, ocr_engine=None, skip_ocr=True)

    assert stats.scanned == 1   # only the Bills one
    assert stats.appended == 1
    records = list(log.iter_records())
    assert records[0]["final_category"] == "Bills"
    assert records[0]["final_issuer"] == "FPL"
    assert records[0]["backend"] == "bootstrap-tree"


def test_bootstrap_from_tree_only_categories(temp_dir):
    root = temp_dir
    (root / "Bills" / "FPL" / "2026").mkdir(parents=True)
    _make_blank_pdf(root / "Bills" / "FPL" / "2026" / "a.pdf")
    (root / "Paystubs" / "2026").mkdir(parents=True)
    _make_blank_pdf(root / "Paystubs" / "2026" / "b.pdf")

    log = FeedbackLog(temp_dir / "log.jsonl")
    stats = bootstrap_from_tree(
        root, log, ocr_engine=None, skip_ocr=True,
        only_categories=["Bills"],
    )
    assert stats.scanned == 1
    rec = list(log.iter_records())[0]
    assert rec["final_category"] == "Bills"


def test_bootstrap_from_tree_max_files(temp_dir):
    root = temp_dir
    (root / "Bills" / "FPL" / "2026").mkdir(parents=True)
    for i in range(5):
        _make_blank_pdf(root / "Bills" / "FPL" / "2026" / f"{i}.pdf")

    log = FeedbackLog(temp_dir / "log.jsonl")
    stats = bootstrap_from_tree(root, log, ocr_engine=None, skip_ocr=True, max_files=2)
    assert stats.scanned == 2
    assert stats.appended == 2


def test_bootstrap_from_tree_is_idempotent(temp_dir):
    root = temp_dir
    (root / "Bills" / "FPL" / "2026").mkdir(parents=True)
    _make_blank_pdf(root / "Bills" / "FPL" / "2026" / "a.pdf")

    log = FeedbackLog(temp_dir / "log.jsonl")
    s1 = bootstrap_from_tree(root, log, ocr_engine=None, skip_ocr=True)
    s2 = bootstrap_from_tree(root, log, ocr_engine=None, skip_ocr=True)
    assert s1.appended == 1
    assert s2.appended == 0
    assert s2.already_logged == 1
